package com.bulletjournal.contents;

public enum ContentAction {
    ADD_PROJECT, DELETE_PROJECT, UPDATE_PROJECT, ADD_TASK, DELETE_TASK, UPDATE_TASK, ADD_NOTE, DELETE_NOTE, UPDATE_NOTE,
    ADD_TRANSACTION, DELETE_TRANSACTION, UPDATE_TRANSACTION, ADD_GROUP, DELETE_GROUP, UPDATE_GROUP, ADD_LABEL,
    DELETE_LABEL, UPDATE_LABEL, ADD_CONTENT, DELETE_CONTENT, UPDATE_CONTENT,
}
