// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: daemon/grpc/types/join_group_events.proto

package types

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetUser      string `protobuf:"bytes,1,opt,name=targetUser,proto3" json:"targetUser,omitempty"`
	ContentId       uint64 `protobuf:"varint,2,opt,name=contentId,proto3" json:"contentId,omitempty"`
	ContentName     string `protobuf:"bytes,3,opt,name=contentName,proto3" json:"contentName,omitempty"`
	OriginatorAlias string `protobuf:"bytes,4,opt,name=originatorAlias,proto3" json:"originatorAlias,omitempty"`
	NotificationId  uint64 `protobuf:"varint,5,opt,name=notificationId,proto3" json:"notificationId,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_grpc_types_join_group_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_grpc_types_join_group_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_daemon_grpc_types_join_group_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTargetUser() string {
	if x != nil {
		return x.TargetUser
	}
	return ""
}

func (x *Event) GetContentId() uint64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *Event) GetContentName() string {
	if x != nil {
		return x.ContentName
	}
	return ""
}

func (x *Event) GetOriginatorAlias() string {
	if x != nil {
		return x.OriginatorAlias
	}
	return ""
}

func (x *Event) GetNotificationId() uint64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type JoinGroupEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events     []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Originator string   `protobuf:"bytes,2,opt,name=originator,proto3" json:"originator,omitempty"`
}

func (x *JoinGroupEvent) Reset() {
	*x = JoinGroupEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_grpc_types_join_group_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGroupEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupEvent) ProtoMessage() {}

func (x *JoinGroupEvent) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_grpc_types_join_group_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupEvent.ProtoReflect.Descriptor instead.
func (*JoinGroupEvent) Descriptor() ([]byte, []int) {
	return file_daemon_grpc_types_join_group_events_proto_rawDescGZIP(), []int{1}
}

func (x *JoinGroupEvent) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *JoinGroupEvent) GetOriginator() string {
	if x != nil {
		return x.Originator
	}
	return ""
}

type JoinGroupEvents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinGroupEvents []*JoinGroupEvent `protobuf:"bytes,1,rep,name=joinGroupEvents,proto3" json:"joinGroupEvents,omitempty"`
}

func (x *JoinGroupEvents) Reset() {
	*x = JoinGroupEvents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_grpc_types_join_group_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGroupEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupEvents) ProtoMessage() {}

func (x *JoinGroupEvents) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_grpc_types_join_group_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupEvents.ProtoReflect.Descriptor instead.
func (*JoinGroupEvents) Descriptor() ([]byte, []int) {
	return file_daemon_grpc_types_join_group_events_proto_rawDescGZIP(), []int{2}
}

func (x *JoinGroupEvents) GetJoinGroupEvents() []*JoinGroupEvent {
	if x != nil {
		return x.JoinGroupEvents
	}
	return nil
}

type ReplyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_grpc_types_join_group_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_grpc_types_join_group_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_daemon_grpc_types_join_group_events_proto_rawDescGZIP(), []int{3}
}

func (x *ReplyMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_daemon_grpc_types_join_group_events_proto protoreflect.FileDescriptor

var file_daemon_grpc_types_join_group_events_proto_rawDesc = []byte{
	0x0a, 0x29, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x22, 0xb9, 0x01, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f,
	0x72, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x56,
	0x0a, 0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x24, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x52, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x3f, 0x0a, 0x0f, 0x6a, 0x6f, 0x69,
	0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0f, 0x6a, 0x6f, 0x69, 0x6e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x28, 0x0a, 0x0c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x80, 0x01, 0x0a, 0x2c, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x75, 0x6c,
	0x6c, 0x65, 0x74, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x42, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x01, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x64, 0x6d, 0x78, 0x2f, 0x42,
	0x75, 0x6c, 0x6c, 0x65, 0x74, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daemon_grpc_types_join_group_events_proto_rawDescOnce sync.Once
	file_daemon_grpc_types_join_group_events_proto_rawDescData = file_daemon_grpc_types_join_group_events_proto_rawDesc
)

func file_daemon_grpc_types_join_group_events_proto_rawDescGZIP() []byte {
	file_daemon_grpc_types_join_group_events_proto_rawDescOnce.Do(func() {
		file_daemon_grpc_types_join_group_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_daemon_grpc_types_join_group_events_proto_rawDescData)
	})
	return file_daemon_grpc_types_join_group_events_proto_rawDescData
}

var file_daemon_grpc_types_join_group_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_daemon_grpc_types_join_group_events_proto_goTypes = []interface{}{
	(*Event)(nil),           // 0: types.Event
	(*JoinGroupEvent)(nil),  // 1: types.JoinGroupEvent
	(*JoinGroupEvents)(nil), // 2: types.JoinGroupEvents
	(*ReplyMessage)(nil),    // 3: types.ReplyMessage
}
var file_daemon_grpc_types_join_group_events_proto_depIdxs = []int32{
	0, // 0: types.JoinGroupEvent.events:type_name -> types.Event
	1, // 1: types.JoinGroupEvents.joinGroupEvents:type_name -> types.JoinGroupEvent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_daemon_grpc_types_join_group_events_proto_init() }
func file_daemon_grpc_types_join_group_events_proto_init() {
	if File_daemon_grpc_types_join_group_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_daemon_grpc_types_join_group_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_grpc_types_join_group_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGroupEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_grpc_types_join_group_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGroupEvents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_grpc_types_join_group_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daemon_grpc_types_join_group_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_daemon_grpc_types_join_group_events_proto_goTypes,
		DependencyIndexes: file_daemon_grpc_types_join_group_events_proto_depIdxs,
		MessageInfos:      file_daemon_grpc_types_join_group_events_proto_msgTypes,
	}.Build()
	File_daemon_grpc_types_join_group_events_proto = out.File
	file_daemon_grpc_types_join_group_events_proto_rawDesc = nil
	file_daemon_grpc_types_join_group_events_proto_goTypes = nil
	file_daemon_grpc_types_join_group_events_proto_depIdxs = nil
}
