INSERT INTO "template".sample_tasks (id,created_at,updated_at,metadata,content,name,uid) VALUES (1114,'2020-08-29 10:21:46.593','2020-08-29 10:21:46.593','LEETCODE_CONCURRENCY,Easy','{"delta":{"ops":[{"attributes":{"bold":true},"insert":"Easy"},{"insert":"Link: "},{"attributes":{"link":"https://leetcode.com/problems/print-in-order/"},"insert":"https://leetcode.com/problems/print-in-order/"},{"insert":"\n"}]},"###html###":"<p><strong>Easy</strong></p><p>Link: <a href=\"https://leetcode.com/problems/print-in-order/\" rel=\"noopener noreferrer\" target=\"_blank\">https://leetcode.com/problems/print-in-order/</a></p>"}','1114 Print in Order','1114');
INSERT INTO "template".sample_tasks (id,created_at,updated_at,metadata,content,name,uid) VALUES (1115,'2020-08-29 10:21:46.593','2020-08-29 10:21:46.593','LEETCODE_CONCURRENCY,Medium','{“delta":{"ops":[{"attributes":{"bold":true},"insert":"Medium"},{"insert":"Link: "},{"attributes":{"link":"https://leetcode.com/problems/print-foobar-alternately/"},"insert":"https://leetcode.com/problems/print-foobar-alternately/"},{"insert":"\n"}]},"###html###":"<p><strong>Medium</strong></p><p>Link: <a href=\"https://leetcode.com/problems/print-foobar-alternately/\" rel=\"noopener noreferrer\" target=\"_blank\">https://leetcode.com/problems/print-foobar-alternately/</a></p>"}','1115 Print FooBar Alternately','1115');
INSERT INTO "template".sample_tasks (id,created_at,updated_at,metadata,content,name,uid) VALUES (1116,'2020-08-29 10:21:46.593','2020-08-29 10:21:46.593','LEETCODE_CONCURRENCY,Medium','{“delta":{"ops":[{"attributes":{"bold":true},"insert":"Medium"},{"insert":"Link: "},{"attributes":{"link":"https://leetcode.com/problems/print-zero-even-odd/"},"insert":"https://leetcode.com/problems/print-zero-even-odd/"},{"insert":"\n"}]},"###html###":"<p><strong>Medium</strong></p><p>Link: <a href=\"https://leetcode.com/problems/print-zero-even-odd/\" rel=\"noopener noreferrer\" target=\"_blank\">https://leetcode.com/problems/print-zero-even-odd/</a></p>"}','1116 Print Zero Even Odd','1116');
INSERT INTO "template".sample_tasks (id,created_at,updated_at,metadata,content,name,uid) VALUES (1117,'2020-08-29 10:21:46.593','2020-08-29 10:21:46.593','LEETCODE_CONCURRENCY,Medium','{“delta":{"ops":[{"attributes":{"bold":true},"insert":"Medium"},{"insert":"Link: "},{"attributes":{"link":"https://leetcode.com/problems/building-h2o/"},"insert":"https://leetcode.com/problems/building-h2o/"},{"insert":"\n"}]},"###html###":"<p><strong>Medium</strong></p><p>Link: <a href=\"https://leetcode.com/problems/building-h2o/\" rel=\"noopener noreferrer\" target=\"_blank\">https://leetcode.com/problems/building-h2o/</a></p>"}','1117 Building H2O','1117');
INSERT INTO "template".sample_tasks (id,created_at,updated_at,metadata,content,name,uid) VALUES (1188,'2020-08-29 10:21:46.593','2020-08-29 10:21:46.593','LEETCODE_CONCURRENCY,Medium','{“delta":{"ops":[{"attributes":{"bold":true},"insert":"Medium"},{"insert":"Link: "},{"attributes":{"link":"https://leetcode.com/problems/design-bounded-blocking-queue/"},"insert":"https://leetcode.com/problems/design-bounded-blocking-queue/"},{"insert":"\n"}]},"###html###":"<p><strong>Medium</strong></p><p>Link: <a href=\"https://leetcode.com/problems/design-bounded-blocking-queue/\" rel=\"noopener noreferrer\" target=\"_blank\">https://leetcode.com/problems/design-bounded-blocking-queue/</a></p>"}','1188 Design Bounded Blocking Queue','1188');
INSERT INTO "template".sample_tasks (id,created_at,updated_at,metadata,content,name,uid) VALUES (1195,'2020-08-29 10:21:46.593','2020-08-29 10:21:46.593','LEETCODE_CONCURRENCY,Medium','{“delta":{"ops":[{"attributes":{"bold":true},"insert":"Medium"},{"insert":"Link: "},{"attributes":{"link":"https://leetcode.com/problems/fizz-buzz-multithreaded/"},"insert":"https://leetcode.com/problems/fizz-buzz-multithreaded/"},{"insert":"\n"}]},"###html###":"<p><strong>Medium</strong></p><p>Link: <a href=\"https://leetcode.com/problems/fizz-buzz-multithreaded/\" rel=\"noopener noreferrer\" target=\"_blank\">https://leetcode.com/problems/fizz-buzz-multithreaded/</a></p>"}','1195 Fizz Buzz Multithreaded','1195');
INSERT INTO "template".sample_tasks (id,created_at,updated_at,metadata,content,name,uid) VALUES (1226,'2020-08-29 10:21:46.593','2020-08-29 10:21:46.593','LEETCODE_CONCURRENCY,Medium','{“delta":{"ops":[{"attributes":{"bold":true},"insert":"Medium"},{"insert":"Link: "},{"attributes":{"link":"https://leetcode.com/problems/the-dining-philosophers/"},"insert":"https://leetcode.com/problems/the-dining-philosophers/"},{"insert":"\n"}]},"###html###":"<p><strong>Medium</strong></p><p>Link: <a href=\"https://leetcode.com/problems/the-dining-philosophers/\" rel=\"noopener noreferrer\" target=\"_blank\">https://leetcode.com/problems/the-dining-philosophers/</a></p>"}','1226 The Dining Philosophers','1226');
INSERT INTO "template".sample_tasks (id,created_at,updated_at,metadata,content,name,uid) VALUES (1279,'2020-08-29 10:21:46.593','2020-08-29 10:21:46.593','LEETCODE_CONCURRENCY,Easy','{"delta":{"ops":[{"attributes":{"bold":true},"insert":"Easy"},{"insert":"Link: "},{"attributes":{"link":"https://leetcode.com/problems/traffic-light-controlled-intersection/"},"insert":"https://leetcode.com/problems/traffic-light-controlled-intersection/"},{"insert":"\n"}]},"###html###":"<p><strong>Easy</strong></p><p>Link: <a href=\"https://leetcode.com/problems/traffic-light-controlled-intersection/\" rel=\"noopener noreferrer\" target=\"_blank\">https://leetcode.com/problems/traffic-light-controlled-intersection/</a></p>"}','1279 Traffic Light Controlled Intersection','1279');


INSERT INTO template.steps (id, created_at, updated_at, name, excluded_selections, next_step, choice_order)
VALUES (20, '2020-10-04 14:49:41.000000', '2020-10-04 14:49:45.000000', 'leetcode concurrency final step', null, null, null);

INSERT INTO template.steps (id, created_at, updated_at, name, excluded_selections, next_step, choice_order)
VALUES (19, '2020-10-04 14:49:34.000000', '2020-10-04 14:49:39.000000', 'leetcode concurrency first step', null, 20, null);


INSERT INTO template.selection_metadata_keywords (keyword, created_at, updated_at, selection_id)
VALUES ('LEETCODE_CONCURRENCY', '2020-10-04 14:53:52.000000', '2020-10-04 14:53:55.000000', 55);

UPDATE template.steps
SET excluded_selections = '{15}'
WHERE id = 19;

INSERT INTO template.choices_steps (choice_id, step_id)
VALUES (11, 19);

INSERT INTO template.category_rules (id, name, created_at, updated_at, rule_expression, priority, category_id,
                                     connected_step_id)
VALUES (13, 'CS concurrency rule', '2020-10-04 21:27:01.000000', '2020-10-04 21:27:03.000000',
        '{"rule":[{"condition":"CONTAINS","selectionIds":[55]}],"logicOperator":AND}', 0, 13, 19);

INSERT INTO template.sample_task_rules (task_ids, step_id, selection_combo) VALUES ('1114,1279', 20, '11');
INSERT INTO template.sample_task_rules (task_ids, step_id, selection_combo) VALUES ('1115,1116,1117,1188,1195,1226', 20, '13');