UPDATE template.sample_tasks
SET content = '{"delta":{"ops":[{"attributes":{"bold":true},"insert":"Date"},{"insert":": 2020-10-16\n"},{"attributes":{"bold":true},"insert":"Time"},{"insert":": 06:04:38\n"},{"attributes":{"bold":true},"insert":"Ticker"},{"insert":": OPT\n"},{"attributes":{"bold":true},"insert":"Exchange"},{"insert":": NASDAQ\n"},{"attributes":{"bold":true},"insert":"Name"},{"insert":": Opthea Ltd\n"},{"attributes":{"bold":true},"insert":"Pricing Date"},{"insert":": 2020-10-15\n"},{"attributes":{"bold":true},"insert":"Currency"},{"insert":": USD\n"},{"attributes":{"bold":true},"insert":"Offering Shares"},{"insert":": 9300000\n"},{"attributes":{"bold":true},"insert":"Lead Underwriters: "},{"insert": "Citigroup, SVB Leerink\n"} ]},"###html###":"<p><strong>Date</strong>: 2020-10-16</p><p><strong>Time</strong>: 06:04:38</p><p><strong>Ticker</strong>: OPT</p><p><strong>Exchange</strong>: NASDAQ</p><p><strong>Name</strong>: Opthea Ltd</p><p><strong>Pricing Date</strong>: 2020-10-15</p><p><strong>Currency</strong>: USD</p><p><strong>Offering Shares</strong>: 9300000</p><p><strong>Lead Underwriters</strong>: Citigroup, SVB Leerink</p> "}'
WHERE id = 5003;

UPDATE template.sample_tasks
SET content = '{"delta":{"ops":[{"attributes":{"bold":true},"insert":"Date"},{"insert":": 2020-10-15\n"},{"attributes":{"bold":true},"insert":"Time"},{"insert":": 05:36:25\n"},{"attributes":{"bold":true},"insert":"Ticker"},{"insert":": MOTNU\n"},{"attributes":{"bold":true},"insert":"Exchange"},{"insert":": NASDAQ\n"},{"attributes":{"bold":true},"insert":"Name"},{"insert":": Motion Acquisition Corp\n"},{"attributes":{"bold":true},"insert":"Pricing Date"},{"insert":": 2020-10-15\n"},{"attributes":{"bold":true},"insert":"Currency"},{"insert":": USD\n"},{"attributes":{"bold":true},"insert":"Price Range"},{"insert":": 10.000\n"},{"attributes":{"bold":true},"insert":"Offering Shares"},{"insert":": 11500000\n"},{"attributes":{"bold":true},"insert":"Lead Underwriters: "},{"insert": "Barclays\n"} ]},"###html###":"<p><strong>Date</strong>: 2020-10-15</p><p><strong>Time</strong>: 05:36:25</p><p><strong>Ticker</strong>: MOTNU</p><p><strong>Exchange</strong>: NASDAQ</p><p><strong>Name</strong>: Motion Acquisition Corp</p><p><strong>Pricing Date</strong>: 2020-10-15</p><p><strong>Currency</strong>: USD</p><p><strong>Price Range</strong>: 10.000</p><p><strong>Offering Shares</strong>: 11500000</p><p><strong>Lead Underwriters</strong>: Barclays</p> "}'
    WHERE id = 5002;

UPDATE template.sample_tasks
SET content = '{"delta":{"ops":[{"attributes":{"bold":true},"insert":"Date"},{"insert":": 2020-10-15\n"},{"attributes":{"bold":true},"insert":"Time"},{"insert":": 04:29:18\n"},{"attributes":{"bold":true},"insert":"Ticker"},{"insert":": MNSO\n"},{"attributes":{"bold":true},"insert":"Exchange"},{"insert":": NYSE\n"},{"attributes":{"bold":true},"insert":"Name"},{"insert":": MINISO Group Holding Ltd\n"},{"attributes":{"bold":true},"insert":"Pricing Date"},{"insert":": 2020-10-15\n"},{"attributes":{"bold":true},"insert":"Currency"},{"insert":": USD\n"},{"attributes":{"bold":true},"insert":"Price Range"},{"insert":": 20.000\n"},{"attributes":{"bold":true},"insert":"Offering Shares"},{"insert":": 30400000\n"},{"attributes":{"bold":true},"insert":"Lead Underwriters: "},{"insert": "Goldman Sachs, Bank of America\n"} ]},"###html###":"<p><strong>Date</strong>: 2020-10-15</p><p><strong>Time</strong>: 04:29:18</p><p><strong>Ticker</strong>: MNSO</p><p><strong>Exchange</strong>: NYSE</p><p><strong>Name</strong>: MINISO Group Holding Ltd</p><p><strong>Pricing Date</strong>: 2020-10-15</p><p><strong>Currency</strong>: USD</p><p><strong>Price Range</strong>: 20.000</p><p><strong>Offering Shares</strong>: 30400000</p><p><strong>Lead Underwriters</strong>: Goldman Sachs, Bank of America</p> "}'
    WHERE id = 5001;

UPDATE template.sample_tasks
SET content = '{"delta":{"ops":[{"attributes":{"bold":true},"insert":"Date"},{"insert":": 2020-10-15\n"},{"attributes":{"bold":true},"insert":"Time"},{"insert":": 04:23:14\n"},{"attributes":{"bold":true},"insert":"Ticker"},{"insert":": TMTSU\n"},{"attributes":{"bold":true},"insert":"Exchange"},{"insert":": NASDAQ\n"},{"attributes":{"bold":true},"insert":"Name"},{"insert":": Spartacus Acquisition Corporation\n"},{"attributes":{"bold":true},"insert":"Pricing Date"},{"insert":": 2020-10-15\n"},{"attributes":{"bold":true},"insert":"Currency"},{"insert":": USD\n"},{"attributes":{"bold":true},"insert":"Price Range"},{"insert":": 10.000\n"},{"attributes":{"bold":true},"insert":"Offering Shares"},{"insert":": 20000000\n"},{"attributes":{"bold":true},"insert":"Lead Underwriters: "},{"insert": "B. Riley FBR\n"} ]},"###html###":"<p><strong>Date</strong>: 2020-10-15</p><p><strong>Time</strong>: 04:23:14</p><p><strong>Ticker</strong>: TMTSU</p><p><strong>Exchange</strong>: NASDAQ</p><p><strong>Name</strong>: Spartacus Acquisition Corporation</p><p><strong>Pricing Date</strong>: 2020-10-15</p><p><strong>Currency</strong>: USD</p><p><strong>Price Range</strong>: 10.000</p><p><strong>Offering Shares</strong>: 20000000</p><p><strong>Lead Underwriters</strong>: B. Riley FBR</p> "}'
    WHERE id = 5000;

alter table template.sample_tasks alter column name type varchar(500) using name::varchar(500);
alter table tasks alter column name type varchar(500) using name::varchar(500);
alter table notes alter column name type varchar(500) using name::varchar(500);
alter table transactions alter column name type varchar(500) using name::varchar(500);