USERNAME: postgres
PASSWORD: docker
DATABASE: postgres
DBPORT: 5432
RPCPORT: 50051
REDISPORT: 6379
HTTPPORT: 9091
DBDRIVER: postgresql
APIKEYPUBLIC: MJ_APIKEY_PUBLIC_DAEMON
APIKEYPRIVATE: MJ_APIKEY_PRIVATE_DAEMON
SENDEREMAIL: SENDER_EMAIL_DAEMON
SENDERNAME: SENDER_NAME